# frozen_string_literal: true

source 'https://rubygems.org'
gem 'rubyXL'
gem 'kybus-bot'
gem 'kybus-logger'
gem 'kybus-configs'
gem 'httparty'
gem 'kybus-core'
gem 'kybus-storage'
gem 'open-weather-ruby-client'
gem 'pry'
gem 'rake'
gem 'sequel'
gem 'sqlite3'
gem 'amazing_print'
gem 'activerecord'
gem 'telegram-bot-ruby'
group :development do
  gem 'mocha'
  gem 'rack'
  gem 'rack-minitest'
  gem 'simplecov'
  gem 'webmock'
end
